name: Build and Distribute Addons

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Ubuntu dependencies
      run: sudo apt update && sudo apt-get -y install gettext appstream pkg-config libcairo2-dev gir1.2-gtk-3.0 libgirepository1.0-dev libicu-dev gir1.2-pango-1.0
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gramps[GUI,i18n]==5.2.3
    - name: Build Addons
      run: |
        export LANGUAGE=en_US.UTF-8
        python3 make.py gramps52 init all          # Initialize all addons
        python3 make.py gramps52 update all        # Update translations
        python3 make.py gramps52 compile all       # Compile .po to .mo files
        python3 make.py gramps52 build all         # Build addons
        python3 make.py gramps52 listing all       # Update listings
        python3 make.py gramps52 as-needed         # Ensure everything is up to date
    - name: Commit and Push to dist Branch
      run: |
        # Configure Git
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

        # Create or switch to the 'dist' branch
        git checkout -b dist || git checkout dist

        # Add and commit the updated build files
        git add .
        git commit -m "Automated build and distribution of addons"

        # Push changes to the 'dist' branch
        git push origin dist --force
